name: ui_application
description: App for TVBox.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-37.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.2
  video_player: ^2.4.2
  json_serializable: ^6.2.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true